<?php
$title = "Delete cms folder";
$this->headTitle($title);
?>

<h1 id="title"><?php echo $this->escapeHtml($title); ?></h1>

<div id="dashboard">
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('cms/delete', array('action' => 'delete')));
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>

<div class="ui-fieldset">
	<div class="content">
		<?php echo $this->formHidden($form->get('id_cms_folder')); ?>
		<span>Are you sure to remove the CMS key "<?php echo $this->key; ?>"?</span>
		<span>All items from this CMS key will be removed!</span>
	</div>

	<div class="ui-formRow ui-submit-field">
		<div class="ui-formCol2"><?php echo $this->formElement($form->get('submit')); ?></div>
		<div class="ui-formCol2"><?php echo $this->formElement($form->get('cancel')); ?></div>
	</div>
</div>

<?php echo $this->form()->closeTag(); ?>
</div>