<?php
$form = $this->form;
$form->prepare();
//$form->setAttribute('action', $this->url('/pet/product', array('action' => 'product')));
//$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
?>

<h1 id="title">Administration PET</h1>

<div id="dashboard" class="pet-detail__container">
<?php echo $this->formCollection($form); ?>
<div class="illustration-image__container">
	<div class="illustration-image">
		
	</div>
	<input class="open-file" type="file" name="file-open-container" />
</div>
</div>

<?php echo $this->form()->closeTag(); ?>