<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('In Kiến Đông ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/png/favicon16.ico'))
                        ->prependStylesheet($this->basePath('css/bob-style.css'))
                    //    ->prependStylesheet($this->basePath('css/lightbox.css'))
                    //    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                    //    ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bob-main.js'))
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/modernizr-custom.js'))
            ->prependFile($this->basePath('js/lightbox.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/jquery-1.12.0.min.js'))
        ; ?>

    </head>
    <body>
        <?php echo $this->partial('cms/header'); ?>

        <div class="container">
            <?php
            $children = $this->viewModel()
                 ->getCurrent()
                 ->getChildren();
 
            $currentView = $children[0];
 
            if (isset($currentView->flashMessenger) && count($currentView->flashMessenger)) : ?>
                <ul class="flashMessages">
                <?php foreach ($currentView->flashMessenger as $flashMessenger) : ?>
                    <li><?php echo $flashMessenger; ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>

            <?php echo $this->content; ?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
