<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('In Kiến Đông ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => "http://inkiendong.com/" . $this->basePath() . '/img/png/favicon16.ico'))
                        ->prependStylesheet("http://inkiendong.com/" . $this->basePath('css/bob-style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/bob-main.js'))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/main.js'))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/bootstrap.min.js'))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/modernizr-custom.js'))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/lightbox.js'))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile("http://inkiendong.com/" . $this->basePath('js/jquery-1.12.0.min.js'))
        ; ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
