<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="description" content="inkiendong.com" />
		<meta name="keywords" content="inkiendong.com" />
		<title>Trang không tìm thấy - In Kiến Đông</title>
		<style type="text/css">
			.error-container {
  				position: relative;
  				width: 1200px;
  				height: 600px;
  				margin: 0 auto;
			}

			#info-main-text {
				font-family: Calibri, "Segoe UI", Arial;
  				font-size: 26px;
  				font-weight: 500;
  				text-align: center;
			}

			#info-main-text img {
				position: relative;
				top: 70px;
				width: 300px;
			}
				

			#info-main-text a {
				border: 1px solid #000;
				border-radius: 20px;
				padding: 8px 20px 10px 20px;
				text-decoration: none;
				color: #000;
			}

			#info-main-text a:hover {
				background-color: #005da5;
				color: #fff;
			}

			.callback-container {
				position: relative;
				top: 120px;
			}
		</style>
	</head>
	<body>
		<div class="error-container" style="">
			<div id="info-main-text">
				<img src="http://localhost/alice2/public/img/404.jpg" />
				<div class="callback-container">
				<p>Có vẻ trang bạn vừa tìm không tồn tại nữa hoặc đã được di chuyển sang trang khác.</p>
				<p>Vui lòng quay lại trang chủ tại đây</p>
				<a class="back-button" href="http://localhost/alice2/">Trang chủ</a>
				</div>
			</div>
		</div>
	</body>
</html>

